name: Svelte Website guild.
run-name: ${{ github.actor }} is building the website.
on:
  push:
    branches:
      - 'svelte-stable'
jobs:
  build:
    name: 'Building the website'
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: 'Build:checkout'
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: git.projectsegfau.lt
          username: midou
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v3
        with:
          tags: git.projectsegfau.lt/midou/midou36o.github.io:latest
          context: '.'
          push: true
          no-cache: true
