name: Svelte Website guild.
run-name: ${{ github.actor }} is building the website.
on:
  push:
    branches:
      - 'svelte-stable'
jobs:
  build:
    name: 'Building the website'
    runs-on: ubuntu-latest
    steps:
      - name: Install Docker
        run: curl -fsSL https://get.docker.com | sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'Build:checkout'
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: git.projectsegfau.lt
          username: midou
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v5
        env:
          ACTIONS_RUNTIME_TOKEN: '' # Workaround to some bug specific to gitea actions.
        with:
          tags: midou/midou36o.github.io:latest
          context: '.'
          push: true
          no-cache: true
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.ACCESS_TOKEN }}
